Search.appendIndex(
    [
                {
            "fqsen": "\\db_add_note\u0028\u0029",
            "name": "db_add_note",
            "summary": "ADD\u0020NOTE\u0020TO\u0020DATABASE",
            "url": "namespaces/default.html#function_db_add_note"
        },                {
            "fqsen": "\\db_get_all_items\u0028\u0029",
            "name": "db_get_all_items",
            "summary": "GET\u0020ALL\u0020ITEMS",
            "url": "namespaces/default.html#function_db_get_all_items"
        },                {
            "fqsen": "\\filterData\u0028\u0029",
            "name": "filterData",
            "summary": "FILTERS\u0020DATA\u0020FROM\u0020ARRAY",
            "url": "namespaces/default.html#function_filterData"
        },                {
            "fqsen": "\\getNumberOfNotes\u0028\u0029",
            "name": "getNumberOfNotes",
            "summary": "GET\u0020NUMBER\u0020OF\u0020USERS\u0020NOTES",
            "url": "namespaces/default.html#function_getNumberOfNotes"
        },                {
            "fqsen": "\\getUsersNotes\u0028\u0029",
            "name": "getUsersNotes",
            "summary": "GET\u0020NOTES\u0020OF\u0020A\u0020SPECIFIC\u0020USER",
            "url": "namespaces/default.html#function_getUsersNotes"
        },                {
            "fqsen": "\\db_add_user\u0028\u0029",
            "name": "db_add_user",
            "summary": "ADD\u0020USER\u0020TO\u0020DATABASE",
            "url": "namespaces/default.html#function_db_add_user"
        },                {
            "fqsen": "\\getAllUsers\u0028\u0029",
            "name": "getAllUsers",
            "summary": "GET\u0020ALL\u0020USERS\u0020IN\u0020DATABASE",
            "url": "namespaces/default.html#function_getAllUsers"
        },                {
            "fqsen": "\\getUserByUserName\u0028\u0029",
            "name": "getUserByUserName",
            "summary": "GET\u0020AN\u0020USER\u0020FROM\u0020DATABASE",
            "url": "namespaces/default.html#function_getUserByUserName"
        },                {
            "fqsen": "\\getUserByUid\u0028\u0029",
            "name": "getUserByUid",
            "summary": "GET\u0020A\u0020SPECIFIC\u0020USER\u0020BY\u0020ID",
            "url": "namespaces/default.html#function_getUserByUid"
        },                {
            "fqsen": "\\db_mark_as_done\u0028\u0029",
            "name": "db_mark_as_done",
            "summary": "MARK\u0020A\u0020SPECIFIC\u0020NOTE\u0020AS\u0020DONE",
            "url": "namespaces/default.html#function_db_mark_as_done"
        },                {
            "fqsen": "\\db_remove_note\u0028\u0029",
            "name": "db_remove_note",
            "summary": "REMOVE\u0020NOTE\u0020FROM\u0020DATABASE",
            "url": "namespaces/default.html#function_db_remove_note"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
